name: Deploy Spring Boot App with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set execute permissions for mvnw
        run: chmod +x mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Spring Boot application
        run: ./mvnw package -DskipTests=true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-spring-boot-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/your-spring-boot-app:latest

      - name: Create directory and file on server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            mkdir -p /home/root/docker
            touch /home/root/docker/docker-compose-prod.yml

      - name: Copy content of docker-compose-prod.yml to server
        run: |
          scp -i ${{ secrets.SERVER_SSH_KEY }} -P ${{ secrets.SERVER_SSH_PORT }} docker/docker-compose-prod.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/root/docker/docker-compose-prod.yml

      - name: Install Docker Compose on server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version

      - name: Deploy with Docker Compose via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            docker-compose -f /home/root/docker/docker-compose-prod.yml pull
            docker-compose -f /home/root/docker/docker-compose-prod.yml down
            docker-compose -f /home/root/docker/docker-compose-prod.yml up -d
