name: Build and Deploy Spring Boot App with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Spring Boot application
        run: mvn -B package --file pom.xml -DskipTests=true

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker build -t $DOCKER_USERNAME/your-spring-boot-app:latest .
          docker push $DOCKER_USERNAME/your-spring-boot-app:latest

      # Optionnel: Utilisez Docker Compose pour déployer
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
